apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appUserSecret.name }}
  namespace: {{ .Values.cloudNativePG.namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.appUserSecret.username }}
  password: {{ .Values.appUserSecret.password }}
